"""“auto-users”

Revision ID: e5800885ec50
Revises: 6da47019fd2c
Create Date: 2022-05-16 12:48:09.436067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5800885ec50'
down_revision = '6da47019fd2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('budget', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'budget', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'budget', type_='foreignkey')
    op.drop_column('budget', 'owner_id')
    op.drop_table('users')
    # ### end Alembic commands ###
